/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package folhapagamento;

import javax.swing.JOptionPane;

/**
 *
 * @author diogenes
 */
public class Vencimentos extends javax.swing.JFrame {

    /**
     * Creates new form Vencimentos
     */
    public Vencimentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tSalario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tFator = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tID = new javax.swing.JTextField();
        bCadastrar = new javax.swing.JButton();
        bAlterarSalario = new javax.swing.JButton();
        bAlterarDep = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tDependentes = new javax.swing.JTextField();
        bVoltar = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Salário do mês (Deixe zero para manter salário base)");

        tSalario.setText("0");

        jLabel3.setText("Vendas, Peças ou Horas");

        tFator.setText("0");
        tFator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFatorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel4.setText("Vencimentos do mês");

        jLabel6.setText("ID");

        bCadastrar.setText("Cadastrar");
        bCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrarActionPerformed(evt);
            }
        });

        bAlterarSalario.setText("Alterar salário");
        bAlterarSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlterarSalarioActionPerformed(evt);
            }
        });

        bAlterarDep.setText("Alterar dependentes");
        bAlterarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlterarDepActionPerformed(evt);
            }
        });

        jLabel7.setText("Dependentes (Deixe zero para manter o cadastrado)");

        tDependentes.setText("0");

        bVoltar.setText("Voltar");
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tSalario)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bAlterarSalario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCadastrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tID, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tFator))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bAlterarDep)
                                .addGap(103, 103, 103)
                                .addComponent(bVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(tDependentes))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCadastrar)
                    .addComponent(bAlterarSalario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAlterarDep)
                    .addComponent(bVoltar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bAlterarSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlterarSalarioActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(tID.getText())>=0 && Float.parseFloat(tSalario.getText())>0){
            int auxcargo=Main.ids.get(Integer.parseInt(tID.getText())).cargo;
            switch(auxcargo){
                case 1:
                    Main.ids.get(Integer.parseInt(tID.getText())).chefe.setSalariobase(Float.parseFloat(tSalario.getText()));
                    break;
                case 2:
                    Main.ids.get(Integer.parseInt(tID.getText())).vendedor.setSalariobase(Float.parseFloat(tSalario.getText()));
                    break;
                case 3:
                    Main.ids.get(Integer.parseInt(tID.getText())).porpeca.setSalariobase(Float.parseFloat(tSalario.getText()));
                    break;
                case 4:
                    Main.ids.get(Integer.parseInt(tID.getText())).porhora.setSalariobase(Float.parseFloat(tSalario.getText()));
                    break;
                default:
                    break;
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Certifique-se que ID, cargo e salário estejam preenchidos");
        }
        Main.gravador();
    }//GEN-LAST:event_bAlterarSalarioActionPerformed

    private void bAlterarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlterarDepActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(tID.getText())>=0 && Float.parseFloat(tDependentes.getText())>0){
            int auxcargo=Main.ids.get(Integer.parseInt(tID.getText())).cargo;
            switch(auxcargo){
                case 1:
                    Main.ids.get(Integer.parseInt(tID.getText())).chefe.setDependentes(Integer.parseInt(tDependentes.getText()));
                    break;
                case 2:
                    Main.ids.get(Integer.parseInt(tID.getText())).vendedor.setDependentes(Integer.parseInt(tDependentes.getText()));
                    break;
                case 3:
                    Main.ids.get(Integer.parseInt(tID.getText())).porpeca.setDependentes(Integer.parseInt(tDependentes.getText()));
                    break;
                case 4:
                    Main.ids.get(Integer.parseInt(tID.getText())).porhora.setDependentes(Integer.parseInt(tDependentes.getText()));
                    break;
                default:
                    break;
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Certifique-se que ID, cargo e dependentes estejam preenchidos");
        }
        Main.gravador();
    }//GEN-LAST:event_bAlterarDepActionPerformed

    private void bCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastrarActionPerformed
        // TODO add your handling code here:
        float auxganho=0;
        if(Integer.parseInt(tID.getText())>=0){
            int auxcargo=Main.ids.get(Integer.parseInt(tID.getText())).cargo;
            System.err.println(Integer.parseInt(tID.getText()));
            if(Float.parseFloat(tSalario.getText())>0){
                switch(auxcargo){
                    case 1:
                        Main.ids.get(Integer.parseInt(tID.getText())).chefe.setSalariobase(Float.parseFloat(tSalario.getText()));
                        break;
                    case 2:
                        Main.ids.get(Integer.parseInt(tID.getText())).vendedor.setSalariobase(Float.parseFloat(tSalario.getText()));
                        break;
                    case 3:
                        Main.ids.get(Integer.parseInt(tID.getText())).porpeca.setSalariobase(Float.parseFloat(tSalario.getText()));
                        break;
                    case 4:
                        Main.ids.get(Integer.parseInt(tID.getText())).porhora.setSalariobase(Float.parseFloat(tSalario.getText()));
                        break;
                    default:
                        break;
                }
            }
            switch(auxcargo){
                case 1:
                    auxganho=Main.ids.get(Integer.parseInt(tID.getText())).chefe.CalcularGanhos();
                    break;
                case 2:
                    auxganho=Main.ids.get(Integer.parseInt(tID.getText())).vendedor.CalcularGanhos(Integer.parseInt(tFator.getText()));
                    break;
                case 3:
                    auxganho=Main.ids.get(Integer.parseInt(tID.getText())).porpeca.CalcularGanhos(Integer.parseInt(tFator.getText()));
                    break;
                case 4:
                    auxganho=Main.ids.get(Integer.parseInt(tID.getText())).porhora.CalcularGanhos(Integer.parseInt(tFator.getText()));
                    break;
                default:
                    break;
            }
            JOptionPane.showMessageDialog(this, "O ganho calculado foi R$ "+auxganho+"\nPara ver sua folha de pagamento, acesse a página anterior", "Ganho mensal", 1);
        }
        else{
            JOptionPane.showMessageDialog(this, "Certifique-se que ID e cargos estejam preenchidos");
        }
        Main.gravador();
    }//GEN-LAST:event_bCadastrarActionPerformed

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_bVoltarActionPerformed

    private void tFatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFatorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vencimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vencimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vencimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vencimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vencimentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlterarDep;
    private javax.swing.JButton bAlterarSalario;
    private javax.swing.JButton bCadastrar;
    private javax.swing.JButton bVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tDependentes;
    private javax.swing.JTextField tFator;
    private javax.swing.JTextField tID;
    private javax.swing.JTextField tSalario;
    // End of variables declaration//GEN-END:variables
}
